name: highlighter
description: Syntax highlighting for Dart with lots of languages and themes support.
version: 0.1.2
homepage: https://github.com/predatorx7/highlight

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  collection: ^1.15.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.3
  path: ^1.9.0
